name: Azure Container Apps Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v3
      
      - name: Build App
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build ${{ github.workspace }}/src